In [1]:
import sys
import pandas as pd
import numpy as np

print('python version :' + sys.version)
print('pandas version :' + pd.__version__) # its version is hidden
print('numpy version :' + np.__version__) # its version is hidden

python version :3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]
pandas version :0.23.4
numpy version :1.15.1

In [ ]:
filename = r'C:\Users\anshs\00ANSH_PYTHON\04-10-18 [1] NUMPY\PANDAS\cars.csv'
table = pd.read_csv(filename)
#table is the dataframe

In [7]:
filename = r'C:\Users\anshs\00ANSH_PYTHON\04-10-18 [1] NUMPY\PANDAS\cars2.csv'
table = pd.read_csv(filename)
print(">>>", type(table), '\n>>>\n', table)
table

>>> <class 'pandas.core.frame.DataFrame'>
>>>
      year                make                  model
0    2001               ACURA                     CL
1    2001               ACURA                     EL
2    2001               ACURA                INTEGRA
3    2001               ACURA                    MDX
4    2001               ACURA                    NSX
5    2001               ACURA                     RL
6    2001               ACURA                     TL
7    2001          AM GENERAL                 HUMMER
8    2001  AMERICAN IRONHORSE                CLASSIC
9    2001  AMERICAN IRONHORSE                 LEGEND
10   2001  AMERICAN IRONHORSE                 OUTLAW
11   2001  AMERICAN IRONHORSE                 RANGER
12   2001  AMERICAN IRONHORSE                SLAMMER
13   2001  AMERICAN IRONHORSE                  TEJAS
14   2001  AMERICAN IRONHORSE                THUNDER
15   2001             APRILIA           ATLANTIC 500
16   2001             APRILIA      ETV 1000 CAPONORD
17   2001             APRILIA       MOJITO CUSTOM 50
18   2001             APRILIA        MOJITO RETRO 50
19   2001             APRILIA             PEGASO 650
20   2001             APRILIA  RALLY 50 (AIR COOLED)
21   2001             APRILIA                 RS 125
22   2001             APRILIA                 RS 250
23   2001             APRILIA         RST1000 FUTURA
24   2001             APRILIA              RSV MILLE
25   2001             APRILIA            RSV MILLE R
26   2001             APRILIA           SCARABEO 125
27   2001             APRILIA           SCARABEO 150
28   2001             APRILIA         SCARABEO 50 2T
29   2001             APRILIA     SCARABEO 50 DITECH
..    ...                 ...                    ...
248  2001               DODGE                   ATOS
249  2001               DODGE                CARAVAN
250  2001               DODGE                 DAKOTA
251  2001               DODGE                DURANGO
252  2001               DODGE          GRAND CARAVAN
253  2001               DODGE               INTREPID
254  2001               DODGE                   NEON
255  2001               DODGE               RAM 1500
256  2001               DODGE        RAM 1500 PICKUP
257  2001               DODGE         RAM 1500 TRUCK
258  2001               DODGE           RAM 1500 VAN
259  2001               DODGE               RAM 2500
260  2001               DODGE        RAM 2500 PICKUP
261  2001               DODGE         RAM 2500 TRUCK
262  2001               DODGE           RAM 2500 VAN
263  2001               DODGE               RAM 3500
264  2001               DODGE        RAM 3500 PICKUP
265  2001               DODGE         RAM 3500 TRUCK
266  2001               DODGE           RAM 3500 VAN
267  2001               DODGE               RAM 4000
268  2001               DODGE                STRATUS
269  2001               DODGE                  VIPER
270  2001              DUCATI                    748
271  2001              DUCATI          748 MONOPOSTO
272  2001              DUCATI                   748R
273  2001              DUCATI                   748S
274  2001              DUCATI         748S MONOPOSTO
275  2001              DUCATI              750 SPORT
276  2001              DUCATI                    900
277  2001              DUCATI            996 BIPOSTO

[278 rows x 3 columns]

     year                make                  model
0    2001               ACURA                     CL
1    2001               ACURA                     EL
2    2001               ACURA                INTEGRA
3    2001               ACURA                    MDX
4    2001               ACURA                    NSX
5    2001               ACURA                     RL
6    2001               ACURA                     TL
7    2001          AM GENERAL                 HUMMER
8    2001  AMERICAN IRONHORSE                CLASSIC
9    2001  AMERICAN IRONHORSE                 LEGEND
10   2001  AMERICAN IRONHORSE                 OUTLAW
11   2001  AMERICAN IRONHORSE                 RANGER
12   2001  AMERICAN IRONHORSE                SLAMMER
13   2001  AMERICAN IRONHORSE                  TEJAS
14   2001  AMERICAN IRONHORSE                THUNDER
15   2001             APRILIA           ATLANTIC 500
16   2001             APRILIA      ETV 1000 CAPONORD
17   2001             APRILIA       MOJITO CUSTOM 50
18   2001             APRILIA        MOJITO RETRO 50
19   2001             APRILIA             PEGASO 650
20   2001             APRILIA  RALLY 50 (AIR COOLED)
21   2001             APRILIA                 RS 125
22   2001             APRILIA                 RS 250
23   2001             APRILIA         RST1000 FUTURA
24   2001             APRILIA              RSV MILLE
25   2001             APRILIA            RSV MILLE R
26   2001             APRILIA           SCARABEO 125
27   2001             APRILIA           SCARABEO 150
28   2001             APRILIA         SCARABEO 50 2T
29   2001             APRILIA     SCARABEO 50 DITECH
..    ...                 ...                    ...
248  2001               DODGE                   ATOS
249  2001               DODGE                CARAVAN
250  2001               DODGE                 DAKOTA
251  2001               DODGE                DURANGO
252  2001               DODGE          GRAND CARAVAN
253  2001               DODGE               INTREPID
254  2001               DODGE                   NEON
255  2001               DODGE               RAM 1500
256  2001               DODGE        RAM 1500 PICKUP
257  2001               DODGE         RAM 1500 TRUCK
258  2001               DODGE           RAM 1500 VAN
259  2001               DODGE               RAM 2500
260  2001               DODGE        RAM 2500 PICKUP
261  2001               DODGE         RAM 2500 TRUCK
262  2001               DODGE           RAM 2500 VAN
263  2001               DODGE               RAM 3500
264  2001               DODGE        RAM 3500 PICKUP
265  2001               DODGE         RAM 3500 TRUCK
266  2001               DODGE           RAM 3500 VAN
267  2001               DODGE               RAM 4000
268  2001               DODGE                STRATUS
269  2001               DODGE                  VIPER
270  2001              DUCATI                    748
271  2001              DUCATI          748 MONOPOSTO
272  2001              DUCATI                   748R
273  2001              DUCATI                   748S
274  2001              DUCATI         748S MONOPOSTO
275  2001              DUCATI              750 SPORT
276  2001              DUCATI                    900
277  2001              DUCATI            996 BIPOSTO

[278 rows x 3 columns]

In [12]:
# pivoting 
# showing a relation of 3 columns from the data. 
"""
eg this is the table which shows 
- all the car models ever produced in vertical
- all the manufactureres in horizontal
-the year in which manufacturer produced that such car as the  cell value
now, this can't be in some other order like year in vertical, model/make in vertical
because a manufacturer produces many cars in a year,
but a perticular created is manufactured only once. so this govis us a query like
select year,model from table where make='acura' for which it gives nan 
for all those cars the maker 'acura' didn't created and year/ modelname as:

             make=
             acura
------------+------
 CL         |2001
 integra    |1997
 series 5   |NaN           # that's made by BMW, not acura , therfore Nan
 ...
 
"""
print(table.pivot(index='model',columns='make',values='year'))
table.pivot(index='model',columns='make',values='year')

make            ACURA  AM GENERAL  AMERICAN IRONHORSE  APRILIA  ARCTIC CAT  \
model
125 CC            NaN         NaN                 NaN      NaN         NaN
250 2X4           NaN         NaN                 NaN      NaN      2001.0
250 4X4           NaN         NaN                 NaN      NaN      2001.0
250 ENDURO        NaN         NaN                 NaN      NaN         NaN
260 ENDURO        NaN         NaN                 NaN      NaN         NaN
300 2X4           NaN         NaN                 NaN      NaN      2001.0
300 4X4           NaN         NaN                 NaN      NaN      2001.0
300M              NaN         NaN                 NaN      NaN         NaN
320I              NaN         NaN                 NaN      NaN         NaN
323I              NaN         NaN                 NaN      NaN         NaN
325CI             NaN         NaN                 NaN      NaN         NaN
325I              NaN         NaN                 NaN      NaN         NaN
325XI             NaN         NaN                 NaN      NaN         NaN
330CI             NaN         NaN                 NaN      NaN         NaN
330I              NaN         NaN                 NaN      NaN         NaN
330XI             NaN         NaN                 NaN      NaN         NaN
400 2X4           NaN         NaN                 NaN      NaN      2001.0
400 4X4           NaN         NaN                 NaN      NaN      2001.0
50 MX             NaN         NaN                 NaN      NaN         NaN
500 4X4           NaN         NaN                 NaN      NaN      2001.0
500 4X4 AUTO      NaN         NaN                 NaN      NaN      2001.0
525I              NaN         NaN                 NaN      NaN         NaN
530I              NaN         NaN                 NaN      NaN         NaN
540I              NaN         NaN                 NaN      NaN         NaN
600 DT            NaN         NaN                 NaN      NaN         NaN
600 MT            NaN         NaN                 NaN      NaN         NaN
605 ENDURO        NaN         NaN                 NaN      NaN         NaN
740I              NaN         NaN                 NaN      NaN         NaN
740IL             NaN         NaN                 NaN      NaN         NaN
748               NaN         NaN                 NaN      NaN         NaN
...               ...         ...                 ...      ...         ...
X5                NaN         NaN                 NaN      NaN         NaN
Z 120             NaN         NaN                 NaN      NaN      2001.0
Z 120 SNO PRO     NaN         NaN                 NaN      NaN      2001.0
Z 370             NaN         NaN                 NaN      NaN      2001.0
Z 370 ES          NaN         NaN                 NaN      NaN      2001.0
Z 440             NaN         NaN                 NaN      NaN      2001.0
Z 440 ES          NaN         NaN                 NaN      NaN      2001.0
Z 440 SNO PRO     NaN         NaN                 NaN      NaN      2001.0
Z3                NaN         NaN                 NaN      NaN         NaN
Z8                NaN         NaN                 NaN      NaN         NaN
ZL 500 EFI ESR    NaN         NaN                 NaN      NaN      2001.0
ZL 550            NaN         NaN                 NaN      NaN      2001.0
ZL 550 ESR        NaN         NaN                 NaN      NaN      2001.0
ZL 600 EFI        NaN         NaN                 NaN      NaN      2001.0
ZL 600 EFI ESR    NaN         NaN                 NaN      NaN      2001.0
ZL 800 ESR        NaN         NaN                 NaN      NaN      2001.0
ZR 440 SNO PRO    NaN         NaN                 NaN      NaN      2001.0
ZR 500            NaN         NaN                 NaN      NaN      2001.0
ZR 500 EFI        NaN         NaN                 NaN      NaN      2001.0
ZR 500 EFI ESR    NaN         NaN                 NaN      NaN      2001.0
ZR 600            NaN         NaN                 NaN      NaN      2001.0
ZR 600 EFI        NaN         NaN                 NaN      NaN      2001.0
ZR 600 EFI LE     NaN         NaN                 NaN      NaN      2001.0
ZR 600 VEV        NaN         NaN                 NaN      NaN      2001.0
ZR 800            NaN         NaN                 NaN      NaN      2001.0
ZR 800 LE         NaN         NaN                 NaN      NaN      2001.0
ZRT 600           NaN         NaN                 NaN      NaN      2001.0
ZRT 600 LE        NaN         NaN                 NaN      NaN      2001.0
ZRT 800           NaN         NaN                 NaN      NaN      2001.0
ZRT 800 LE        NaN         NaN                 NaN      NaN      2001.0

make            ASTON MARTIN     ATK  AUDI  AVANTI  BENTLEY   ...    BUICK  \
model                                                         ...
125 CC                   NaN  2001.0   NaN     NaN      NaN   ...      NaN
250 2X4                  NaN     NaN   NaN     NaN      NaN   ...      NaN
250 4X4                  NaN     NaN   NaN     NaN      NaN   ...      NaN
250 ENDURO               NaN  2001.0   NaN     NaN      NaN   ...      NaN
260 ENDURO               NaN  2001.0   NaN     NaN      NaN   ...      NaN
300 2X4                  NaN     NaN   NaN     NaN      NaN   ...      NaN
300 4X4                  NaN     NaN   NaN     NaN      NaN   ...      NaN
300M                     NaN     NaN   NaN     NaN      NaN   ...      NaN
320I                     NaN     NaN   NaN     NaN      NaN   ...      NaN
323I                     NaN     NaN   NaN     NaN      NaN   ...      NaN
325CI                    NaN     NaN   NaN     NaN      NaN   ...      NaN
325I                     NaN     NaN   NaN     NaN      NaN   ...      NaN
325XI                    NaN     NaN   NaN     NaN      NaN   ...      NaN
330CI                    NaN     NaN   NaN     NaN      NaN   ...      NaN
330I                     NaN     NaN   NaN     NaN      NaN   ...      NaN
330XI                    NaN     NaN   NaN     NaN      NaN   ...      NaN
400 2X4                  NaN     NaN   NaN     NaN      NaN   ...      NaN
400 4X4                  NaN     NaN   NaN     NaN      NaN   ...      NaN
50 MX                    NaN  2001.0   NaN     NaN      NaN   ...      NaN
500 4X4                  NaN     NaN   NaN     NaN      NaN   ...      NaN
500 4X4 AUTO             NaN     NaN   NaN     NaN      NaN   ...      NaN
525I                     NaN     NaN   NaN     NaN      NaN   ...      NaN
530I                     NaN     NaN   NaN     NaN      NaN   ...      NaN
540I                     NaN     NaN   NaN     NaN      NaN   ...      NaN
600 DT                   NaN  2001.0   NaN     NaN      NaN   ...      NaN
600 MT                   NaN  2001.0   NaN     NaN      NaN   ...      NaN
605 ENDURO               NaN  2001.0   NaN     NaN      NaN   ...      NaN
740I                     NaN     NaN   NaN     NaN      NaN   ...      NaN
740IL                    NaN     NaN   NaN     NaN      NaN   ...      NaN
748                      NaN     NaN   NaN     NaN      NaN   ...      NaN
...                      ...     ...   ...     ...      ...   ...      ...
X5                       NaN     NaN   NaN     NaN      NaN   ...      NaN
Z 120                    NaN     NaN   NaN     NaN      NaN   ...      NaN
Z 120 SNO PRO            NaN     NaN   NaN     NaN      NaN   ...      NaN
Z 370                    NaN     NaN   NaN     NaN      NaN   ...      NaN
Z 370 ES                 NaN     NaN   NaN     NaN      NaN   ...      NaN
Z 440                    NaN     NaN   NaN     NaN      NaN   ...      NaN
Z 440 ES                 NaN     NaN   NaN     NaN      NaN   ...      NaN
Z 440 SNO PRO            NaN     NaN   NaN     NaN      NaN   ...      NaN
Z3                       NaN     NaN   NaN     NaN      NaN   ...      NaN
Z8                       NaN     NaN   NaN     NaN      NaN   ...      NaN
ZL 500 EFI ESR           NaN     NaN   NaN     NaN      NaN   ...      NaN
ZL 550                   NaN     NaN   NaN     NaN      NaN   ...      NaN
ZL 550 ESR               NaN     NaN   NaN     NaN      NaN   ...      NaN
ZL 600 EFI               NaN     NaN   NaN     NaN      NaN   ...      NaN
ZL 600 EFI ESR           NaN     NaN   NaN     NaN      NaN   ...      NaN
ZL 800 ESR               NaN     NaN   NaN     NaN      NaN   ...      NaN
ZR 440 SNO PRO           NaN     NaN   NaN     NaN      NaN   ...      NaN
ZR 500                   NaN     NaN   NaN     NaN      NaN   ...      NaN
ZR 500 EFI               NaN     NaN   NaN     NaN      NaN   ...      NaN
ZR 500 EFI ESR           NaN     NaN   NaN     NaN      NaN   ...      NaN
ZR 600                   NaN     NaN   NaN     NaN      NaN   ...      NaN
ZR 600 EFI               NaN     NaN   NaN     NaN      NaN   ...      NaN
ZR 600 EFI LE            NaN     NaN   NaN     NaN      NaN   ...      NaN
ZR 600 VEV               NaN     NaN   NaN     NaN      NaN   ...      NaN
ZR 800                   NaN     NaN   NaN     NaN      NaN   ...      NaN
ZR 800 LE                NaN     NaN   NaN     NaN      NaN   ...      NaN
ZRT 600                  NaN     NaN   NaN     NaN      NaN   ...      NaN
ZRT 600 LE               NaN     NaN   NaN     NaN      NaN   ...      NaN
ZRT 800                  NaN     NaN   NaN     NaN      NaN   ...      NaN
ZRT 800 LE               NaN     NaN   NaN     NaN      NaN   ...      NaN

make            CADILLAC  CANNONDALE  CHANCE COACH TRANSIT BUS  CHEVROLET  \
model
125 CC               NaN         NaN                       NaN        NaN
250 2X4              NaN         NaN                       NaN        NaN
250 4X4              NaN         NaN                       NaN        NaN
250 ENDURO           NaN         NaN                       NaN        NaN
260 ENDURO           NaN         NaN                       NaN        NaN
300 2X4              NaN         NaN                       NaN        NaN
300 4X4              NaN         NaN                       NaN        NaN
300M                 NaN         NaN                       NaN        NaN
320I                 NaN         NaN                       NaN        NaN
323I                 NaN         NaN                       NaN        NaN
325CI                NaN         NaN                       NaN        NaN
325I                 NaN         NaN                       NaN        NaN
325XI                NaN         NaN                       NaN        NaN
330CI                NaN         NaN                       NaN        NaN
330I                 NaN         NaN                       NaN        NaN
330XI                NaN         NaN                       NaN        NaN
400 2X4              NaN         NaN                       NaN        NaN
400 4X4              NaN         NaN                       NaN        NaN
50 MX                NaN         NaN                       NaN        NaN
500 4X4              NaN         NaN                       NaN        NaN
500 4X4 AUTO         NaN         NaN                       NaN        NaN
525I                 NaN         NaN                       NaN        NaN
530I                 NaN         NaN                       NaN        NaN
540I                 NaN         NaN                       NaN        NaN
600 DT               NaN         NaN                       NaN        NaN
600 MT               NaN         NaN                       NaN        NaN
605 ENDURO           NaN         NaN                       NaN        NaN
740I                 NaN         NaN                       NaN        NaN
740IL                NaN         NaN                       NaN        NaN
748                  NaN         NaN                       NaN        NaN
...                  ...         ...                       ...        ...
X5                   NaN         NaN                       NaN        NaN
Z 120                NaN         NaN                       NaN        NaN
Z 120 SNO PRO        NaN         NaN                       NaN        NaN
Z 370                NaN         NaN                       NaN        NaN
Z 370 ES             NaN         NaN                       NaN        NaN
Z 440                NaN         NaN                       NaN        NaN
Z 440 ES             NaN         NaN                       NaN        NaN
Z 440 SNO PRO        NaN         NaN                       NaN        NaN
Z3                   NaN         NaN                       NaN        NaN
Z8                   NaN         NaN                       NaN        NaN
ZL 500 EFI ESR       NaN         NaN                       NaN        NaN
ZL 550               NaN         NaN                       NaN        NaN
ZL 550 ESR           NaN         NaN                       NaN        NaN
ZL 600 EFI           NaN         NaN                       NaN        NaN
ZL 600 EFI ESR       NaN         NaN                       NaN        NaN
ZL 800 ESR           NaN         NaN                       NaN        NaN
ZR 440 SNO PRO       NaN         NaN                       NaN        NaN
ZR 500               NaN         NaN                       NaN        NaN
ZR 500 EFI           NaN         NaN                       NaN        NaN
ZR 500 EFI ESR       NaN         NaN                       NaN        NaN
ZR 600               NaN         NaN                       NaN        NaN
ZR 600 EFI           NaN         NaN                       NaN        NaN
ZR 600 EFI LE        NaN         NaN                       NaN        NaN
ZR 600 VEV           NaN         NaN                       NaN        NaN
ZR 800               NaN         NaN                       NaN        NaN
ZR 800 LE            NaN         NaN                       NaN        NaN
ZRT 600              NaN         NaN                       NaN        NaN
ZRT 600 LE           NaN         NaN                       NaN        NaN
ZRT 800              NaN         NaN                       NaN        NaN
ZRT 800 LE           NaN         NaN                       NaN        NaN

make            CHRYSLER  COBRA  DAEWOO  DODGE  DUCATI
model
125 CC               NaN    NaN     NaN    NaN     NaN
250 2X4              NaN    NaN     NaN    NaN     NaN
250 4X4              NaN    NaN     NaN    NaN     NaN
250 ENDURO           NaN    NaN     NaN    NaN     NaN
260 ENDURO           NaN    NaN     NaN    NaN     NaN
300 2X4              NaN    NaN     NaN    NaN     NaN
300 4X4              NaN    NaN     NaN    NaN     NaN
300M              2001.0    NaN     NaN    NaN     NaN
320I                 NaN    NaN     NaN    NaN     NaN
323I                 NaN    NaN     NaN    NaN     NaN
325CI                NaN    NaN     NaN    NaN     NaN
325I                 NaN    NaN     NaN    NaN     NaN
325XI                NaN    NaN     NaN    NaN     NaN
330CI                NaN    NaN     NaN    NaN     NaN
330I                 NaN    NaN     NaN    NaN     NaN
330XI                NaN    NaN     NaN    NaN     NaN
400 2X4              NaN    NaN     NaN    NaN     NaN
400 4X4              NaN    NaN     NaN    NaN     NaN
50 MX                NaN    NaN     NaN    NaN     NaN
500 4X4              NaN    NaN     NaN    NaN     NaN
500 4X4 AUTO         NaN    NaN     NaN    NaN     NaN
525I                 NaN    NaN     NaN    NaN     NaN
530I                 NaN    NaN     NaN    NaN     NaN
540I                 NaN    NaN     NaN    NaN     NaN
600 DT               NaN    NaN     NaN    NaN     NaN
600 MT               NaN    NaN     NaN    NaN     NaN
605 ENDURO           NaN    NaN     NaN    NaN     NaN
740I                 NaN    NaN     NaN    NaN     NaN
740IL                NaN    NaN     NaN    NaN     NaN
748                  NaN    NaN     NaN    NaN  2001.0
...                  ...    ...     ...    ...     ...
X5                   NaN    NaN     NaN    NaN     NaN
Z 120                NaN    NaN     NaN    NaN     NaN
Z 120 SNO PRO        NaN    NaN     NaN    NaN     NaN
Z 370                NaN    NaN     NaN    NaN     NaN
Z 370 ES             NaN    NaN     NaN    NaN     NaN
Z 440                NaN    NaN     NaN    NaN     NaN
Z 440 ES             NaN    NaN     NaN    NaN     NaN
Z 440 SNO PRO        NaN    NaN     NaN    NaN     NaN
Z3                   NaN    NaN     NaN    NaN     NaN
Z8                   NaN    NaN     NaN    NaN     NaN
ZL 500 EFI ESR       NaN    NaN     NaN    NaN     NaN
ZL 550               NaN    NaN     NaN    NaN     NaN
ZL 550 ESR           NaN    NaN     NaN    NaN     NaN
ZL 600 EFI           NaN    NaN     NaN    NaN     NaN
ZL 600 EFI ESR       NaN    NaN     NaN    NaN     NaN
ZL 800 ESR           NaN    NaN     NaN    NaN     NaN
ZR 440 SNO PRO       NaN    NaN     NaN    NaN     NaN
ZR 500               NaN    NaN     NaN    NaN     NaN
ZR 500 EFI           NaN    NaN     NaN    NaN     NaN
ZR 500 EFI ESR       NaN    NaN     NaN    NaN     NaN
ZR 600               NaN    NaN     NaN    NaN     NaN
ZR 600 EFI           NaN    NaN     NaN    NaN     NaN
ZR 600 EFI LE        NaN    NaN     NaN    NaN     NaN
ZR 600 VEV           NaN    NaN     NaN    NaN     NaN
ZR 800               NaN    NaN     NaN    NaN     NaN
ZR 800 LE            NaN    NaN     NaN    NaN     NaN
ZRT 600              NaN    NaN     NaN    NaN     NaN
ZRT 600 LE           NaN    NaN     NaN    NaN     NaN
ZRT 800              NaN    NaN     NaN    NaN     NaN
ZRT 800 LE           NaN    NaN     NaN    NaN     NaN

[276 rows x 26 columns]

make,ACURA,AM GENERAL,AMERICAN IRONHORSE,APRILIA,ARCTIC CAT,ASTON MARTIN,ATK,AUDI,AVANTI,BENTLEY,...,BUICK,CADILLAC,CANNONDALE,CHANCE COACH TRANSIT BUS,CHEVROLET,CHRYSLER,COBRA,DAEWOO,DODGE,DUCATI
model,,,,,,,,,,,,,,,,,,,,,
125 CC,NaN,NaN,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
250 2X4,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
250 4X4,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
250 ENDURO,NaN,NaN,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260 ENDURO,NaN,NaN,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
300 2X4,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
300 4X4,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
300M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN
320I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
325CI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
325I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
325XI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
330CI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
330I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
330XI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
400 2X4,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
400 4X4,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50 MX,NaN,NaN,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
500 4X4,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
500 4X4 AUTO,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
525I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
530I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
540I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
600 DT,NaN,NaN,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
600 MT,NaN,NaN,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
605 ENDURO,NaN,NaN,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
740I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
740IL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
748,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
X5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Z 120,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Z 120 SNO PRO,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Z 370,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Z 370 ES,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Z 440,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Z 440 ES,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Z 440 SNO PRO,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Z3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Z8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZL 500 EFI ESR,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZL 550,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZL 550 ESR,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZL 600 EFI,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZL 600 EFI ESR,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZL 800 ESR,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZR 440 SNO PRO,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZR 500,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZR 500 EFI,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZR 500 EFI ESR,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZR 600,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZR 600 EFI,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZR 600 EFI LE,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZR 600 VEV,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZR 800,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZR 800 LE,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZRT 600,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZRT 600 LE,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZRT 800,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZRT 800 LE,NaN,NaN,NaN,NaN,2001.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
#multi indexing
filename = r'C:\Users\anshs\00ANSH_PYTHON\04-10-18 [1] NUMPY\PANDAS\cars.csv'
table = pd.read_csv(filename, index_col=['Origin', 'Model'])
print(table)
table

                                           MPG  Cylinders  Displacement  \
Origin Model
US     chevrolet chevelle malibu          18.0          8         307.0
       buick skylark 320                  15.0          8         350.0
       plymouth satellite                 18.0          8         318.0
       amc rebel sst                      16.0          8         304.0
       ford torino                        17.0          8         302.0
       ford galaxie 500                   15.0          8         429.0
       chevrolet impala                   14.0          8         454.0
       plymouth fury iii                  14.0          8         440.0
       pontiac catalina                   14.0          8         455.0
       amc ambassador dpl                 15.0          8         390.0
       dodge challenger se                15.0          8         383.0
       plymouth 'cuda 340                 14.0          8         340.0
       chevrolet monte carlo              15.0          8         400.0
       buick estate wagon (sw)            14.0          8         455.0
Japan  toyota corona mark ii              24.0          4         113.0
US     plymouth duster                    22.0          6         198.0
       amc hornet                         18.0          6         199.0
       ford maverick                      21.0          6         200.0
Japan  datsun pl510                       27.0          4          97.0
Europe volkswagen 1131 deluxe sedan       26.0          4          97.0
       peugeot 504                        25.0          4         110.0
       audi 100 ls                        24.0          4         107.0
       saab 99e                           25.0          4         104.0
       bmw 2002                           26.0          4         121.0
US     amc gremlin                        21.0          6         199.0
       ford f250                          10.0          8         360.0
       chevy c20                          10.0          8         307.0
       dodge d200                         11.0          8         318.0
       hi 1200d                            9.0          8         304.0
Japan  datsun pl510                       27.0          4          97.0
...                                        ...        ...           ...
US     chevrolet cavalier wagon           27.0          4         112.0
       chevrolet cavalier 2-door          34.0          4         112.0
       pontiac j2000 se hatchback         31.0          4         112.0
       dodge aries se                     29.0          4         135.0
       pontiac phoenix                    27.0          4         151.0
       ford fairmont futura               24.0          4         140.0
       amc concord dl                     23.0          4         151.0
Europe volkswagen rabbit l                36.0          4         105.0
Japan  mazda glc custom l                 37.0          4          91.0
       mazda glc custom                   31.0          4          91.0
US     plymouth horizon miser             38.0          4         105.0
       mercury lynx l                     36.0          4          98.0
Japan  nissan stanza xe                   36.0          4         120.0
       honda accord                       36.0          4         107.0
       toyota corolla                     34.0          4         108.0
       honda civic                        38.0          4          91.0
       honda civic (auto)                 32.0          4          91.0
       datsun 310 gx                      38.0          4          91.0
US     buick century limited              25.0          6         181.0
       oldsmobile cutlass ciera (diesel)  38.0          6         262.0
       chrysler lebaron medallion         26.0          4         156.0
       ford granada l                     22.0          6         232.0
Japan  toyota celica gt                   32.0          4         144.0
US     dodge charger 2.2                  36.0          4         135.0
       chevrolet camaro                   27.0          4         151.0
       ford mustang gl                    27.0          4         140.0
Europe vw pickup                          44.0          4          97.0
US     dodge rampage                      32.0          4         135.0
       ford ranger                        28.0          4         120.0
       chevy s-10                         31.0          4         119.0

                                          Horsepower  Weight  Acceleration  \
Origin Model
US     chevrolet chevelle malibu               130.0    3504          12.0
       buick skylark 320                       165.0    3693          11.5
       plymouth satellite                      150.0    3436          11.0
       amc rebel sst                           150.0    3433          12.0
       ford torino                             140.0    3449          10.5
       ford galaxie 500                        198.0    4341          10.0
       chevrolet impala                        220.0    4354           9.0
       plymouth fury iii                       215.0    4312           8.5
       pontiac catalina                        225.0    4425          10.0
       amc ambassador dpl                      190.0    3850           8.5
       dodge challenger se                     170.0    3563          10.0
       plymouth 'cuda 340                      160.0    3609           8.0
       chevrolet monte carlo                   150.0    3761           9.5
       buick estate wagon (sw)                 225.0    3086          10.0
Japan  toyota corona mark ii                    95.0    2372          15.0
US     plymouth duster                          95.0    2833          15.5
       amc hornet                               97.0    2774          15.5
       ford maverick                            85.0    2587          16.0
Japan  datsun pl510                             88.0    2130          14.5
Europe volkswagen 1131 deluxe sedan             46.0    1835          20.5
       peugeot 504                              87.0    2672          17.5
       audi 100 ls                              90.0    2430          14.5
       saab 99e                                 95.0    2375          17.5
       bmw 2002                                113.0    2234          12.5
US     amc gremlin                              90.0    2648          15.0
       ford f250                               215.0    4615          14.0
       chevy c20                               200.0    4376          15.0
       dodge d200                              210.0    4382          13.5
       hi 1200d                                193.0    4732          18.5
Japan  datsun pl510                             88.0    2130          14.5
...                                              ...     ...           ...
US     chevrolet cavalier wagon                 88.0    2640          18.6
       chevrolet cavalier 2-door                88.0    2395          18.0
       pontiac j2000 se hatchback               85.0    2575          16.2
       dodge aries se                           84.0    2525          16.0
       pontiac phoenix                          90.0    2735          18.0
       ford fairmont futura                     92.0    2865          16.4
       amc concord dl                            NaN    3035          20.5
Europe volkswagen rabbit l                      74.0    1980          15.3
Japan  mazda glc custom l                       68.0    2025          18.2
       mazda glc custom                         68.0    1970          17.6
US     plymouth horizon miser                   63.0    2125          14.7
       mercury lynx l                           70.0    2125          17.3
Japan  nissan stanza xe                         88.0    2160          14.5
       honda accord                             75.0    2205          14.5
       toyota corolla                           70.0    2245          16.9
       honda civic                              67.0    1965          15.0
       honda civic (auto)                       67.0    1965          15.7
       datsun 310 gx                            67.0    1995          16.2
US     buick century limited                   110.0    2945          16.4
       oldsmobile cutlass ciera (diesel)        85.0    3015          17.0
       chrysler lebaron medallion               92.0    2585          14.5
       ford granada l                          112.0    2835          14.7
Japan  toyota celica gt                         96.0    2665          13.9
US     dodge charger 2.2                        84.0    2370          13.0
       chevrolet camaro                         90.0    2950          17.3
       ford mustang gl                          86.0    2790          15.6
Europe vw pickup                                52.0    2130          24.6
US     dodge rampage                            84.0    2295          11.6
       ford ranger                              79.0    2625          18.6
       chevy s-10                               82.0    2720          19.4

                                          Year
Origin Model
US     chevrolet chevelle malibu            70
       buick skylark 320                    70
       plymouth satellite                   70
       amc rebel sst                        70
       ford torino                          70
       ford galaxie 500                     70
       chevrolet impala                     70
       plymouth fury iii                    70
       pontiac catalina                     70
       amc ambassador dpl                   70
       dodge challenger se                  70
       plymouth 'cuda 340                   70
       chevrolet monte carlo                70
       buick estate wagon (sw)              70
Japan  toyota corona mark ii                70
US     plymouth duster                      70
       amc hornet                           70
       ford maverick                        70
Japan  datsun pl510                         70
Europe volkswagen 1131 deluxe sedan         70
       peugeot 504                          70
       audi 100 ls                          70
       saab 99e                             70
       bmw 2002                             70
US     amc gremlin                          70
       ford f250                            70
       chevy c20                            70
       dodge d200                           70
       hi 1200d                             70
Japan  datsun pl510                         71
...                                        ...
US     chevrolet cavalier wagon             82
       chevrolet cavalier 2-door            82
       pontiac j2000 se hatchback           82
       dodge aries se                       82
       pontiac phoenix                      82
       ford fairmont futura                 82
       amc concord dl                       82
Europe volkswagen rabbit l                  82
Japan  mazda glc custom l                   82
       mazda glc custom                     82
US     plymouth horizon miser               82
       mercury lynx l                       82
Japan  nissan stanza xe                     82
       honda accord                         82
       toyota corolla                       82
       honda civic                          82
       honda civic (auto)                   82
       datsun 310 gx                        82
US     buick century limited                82
       oldsmobile cutlass ciera (diesel)    82
       chrysler lebaron medallion           82
       ford granada l                       82
Japan  toyota celica gt                     82
US     dodge charger 2.2                    82
       chevrolet camaro                     82
       ford mustang gl                      82
Europe vw pickup                            82
US     dodge rampage                        82
       ford ranger                          82
       chevy s-10                           82

[394 rows x 7 columns]

                                           MPG  Cylinders  Displacement  \
Origin Model
US     chevrolet chevelle malibu          18.0          8         307.0
       buick skylark 320                  15.0          8         350.0
       plymouth satellite                 18.0          8         318.0
       amc rebel sst                      16.0          8         304.0
       ford torino                        17.0          8         302.0
       ford galaxie 500                   15.0          8         429.0
       chevrolet impala                   14.0          8         454.0
       plymouth fury iii                  14.0          8         440.0
       pontiac catalina                   14.0          8         455.0
       amc ambassador dpl                 15.0          8         390.0
       dodge challenger se                15.0          8         383.0
       plymouth 'cuda 340                 14.0          8         340.0
       chevrolet monte carlo              15.0          8         400.0
       buick estate wagon (sw)            14.0          8         455.0
Japan  toyota corona mark ii              24.0          4         113.0
US     plymouth duster                    22.0          6         198.0
       amc hornet                         18.0          6         199.0
       ford maverick                      21.0          6         200.0
Japan  datsun pl510                       27.0          4          97.0
Europe volkswagen 1131 deluxe sedan       26.0          4          97.0
       peugeot 504                        25.0          4         110.0
       audi 100 ls                        24.0          4         107.0
       saab 99e                           25.0          4         104.0
       bmw 2002                           26.0          4         121.0
US     amc gremlin                        21.0          6         199.0
       ford f250                          10.0          8         360.0
       chevy c20                          10.0          8         307.0
       dodge d200                         11.0          8         318.0
       hi 1200d                            9.0          8         304.0
Japan  datsun pl510                       27.0          4          97.0
...                                        ...        ...           ...
US     chevrolet cavalier wagon           27.0          4         112.0
       chevrolet cavalier 2-door          34.0          4         112.0
       pontiac j2000 se hatchback         31.0          4         112.0
       dodge aries se                     29.0          4         135.0
       pontiac phoenix                    27.0          4         151.0
       ford fairmont futura               24.0          4         140.0
       amc concord dl                     23.0          4         151.0
Europe volkswagen rabbit l                36.0          4         105.0
Japan  mazda glc custom l                 37.0          4          91.0
       mazda glc custom                   31.0          4          91.0
US     plymouth horizon miser             38.0          4         105.0
       mercury lynx l                     36.0          4          98.0
Japan  nissan stanza xe                   36.0          4         120.0
       honda accord                       36.0          4         107.0
       toyota corolla                     34.0          4         108.0
       honda civic                        38.0          4          91.0
       honda civic (auto)                 32.0          4          91.0
       datsun 310 gx                      38.0          4          91.0
US     buick century limited              25.0          6         181.0
       oldsmobile cutlass ciera (diesel)  38.0          6         262.0
       chrysler lebaron medallion         26.0          4         156.0
       ford granada l                     22.0          6         232.0
Japan  toyota celica gt                   32.0          4         144.0
US     dodge charger 2.2                  36.0          4         135.0
       chevrolet camaro                   27.0          4         151.0
       ford mustang gl                    27.0          4         140.0
Europe vw pickup                          44.0          4          97.0
US     dodge rampage                      32.0          4         135.0
       ford ranger                        28.0          4         120.0
       chevy s-10                         31.0          4         119.0

                                          Horsepower  Weight  Acceleration  \
Origin Model
US     chevrolet chevelle malibu               130.0    3504          12.0
       buick skylark 320                       165.0    3693          11.5
       plymouth satellite                      150.0    3436          11.0
       amc rebel sst                           150.0    3433          12.0
       ford torino                             140.0    3449          10.5
       ford galaxie 500                        198.0    4341          10.0
       chevrolet impala                        220.0    4354           9.0
       plymouth fury iii                       215.0    4312           8.5
       pontiac catalina                        225.0    4425          10.0
       amc ambassador dpl                      190.0    3850           8.5
       dodge challenger se                     170.0    3563          10.0
       plymouth 'cuda 340                      160.0    3609           8.0
       chevrolet monte carlo                   150.0    3761           9.5
       buick estate wagon (sw)                 225.0    3086          10.0
Japan  toyota corona mark ii                    95.0    2372          15.0
US     plymouth duster                          95.0    2833          15.5
       amc hornet                               97.0    2774          15.5
       ford maverick                            85.0    2587          16.0
Japan  datsun pl510                             88.0    2130          14.5
Europe volkswagen 1131 deluxe sedan             46.0    1835          20.5
       peugeot 504                              87.0    2672          17.5
       audi 100 ls                              90.0    2430          14.5
       saab 99e                                 95.0    2375          17.5
       bmw 2002                                113.0    2234          12.5
US     amc gremlin                              90.0    2648          15.0
       ford f250                               215.0    4615          14.0
       chevy c20                               200.0    4376          15.0
       dodge d200                              210.0    4382          13.5
       hi 1200d                                193.0    4732          18.5
Japan  datsun pl510                             88.0    2130          14.5
...                                              ...     ...           ...
US     chevrolet cavalier wagon                 88.0    2640          18.6
       chevrolet cavalier 2-door                88.0    2395          18.0
       pontiac j2000 se hatchback               85.0    2575          16.2
       dodge aries se                           84.0    2525          16.0
       pontiac phoenix                          90.0    2735          18.0
       ford fairmont futura                     92.0    2865          16.4
       amc concord dl                            NaN    3035          20.5
Europe volkswagen rabbit l                      74.0    1980          15.3
Japan  mazda glc custom l                       68.0    2025          18.2
       mazda glc custom                         68.0    1970          17.6
US     plymouth horizon miser                   63.0    2125          14.7
       mercury lynx l                           70.0    2125          17.3
Japan  nissan stanza xe                         88.0    2160          14.5
       honda accord                             75.0    2205          14.5
       toyota corolla                           70.0    2245          16.9
       honda civic                              67.0    1965          15.0
       honda civic (auto)                       67.0    1965          15.7
       datsun 310 gx                            67.0    1995          16.2
US     buick century limited                   110.0    2945          16.4
       oldsmobile cutlass ciera (diesel)        85.0    3015          17.0
       chrysler lebaron medallion               92.0    2585          14.5
       ford granada l                          112.0    2835          14.7
Japan  toyota celica gt                         96.0    2665          13.9
US     dodge charger 2.2                        84.0    2370          13.0
       chevrolet camaro                         90.0    2950          17.3
       ford mustang gl                          86.0    2790          15.6
Europe vw pickup                                52.0    2130          24.6
US     dodge rampage                            84.0    2295          11.6
       ford ranger                              79.0    2625          18.6
       chevy s-10                               82.0    2720          19.4

                                          Year
Origin Model
US     chevrolet chevelle malibu            70
       buick skylark 320                    70
       plymouth satellite                   70
       amc rebel sst                        70
       ford torino                          70
       ford galaxie 500                     70
       chevrolet impala                     70
       plymouth fury iii                    70
       pontiac catalina                     70
       amc ambassador dpl                   70
       dodge challenger se                  70
       plymouth 'cuda 340                   70
       chevrolet monte carlo                70
       buick estate wagon (sw)              70
Japan  toyota corona mark ii                70
US     plymouth duster                      70
       amc hornet                           70
       ford maverick                        70
Japan  datsun pl510                         70
Europe volkswagen 1131 deluxe sedan         70
       peugeot 504                          70
       audi 100 ls                          70
       saab 99e                             70
       bmw 2002                             70
US     amc gremlin                          70
       ford f250                            70
       chevy c20                            70
       dodge d200                           70
       hi 1200d                             70
Japan  datsun pl510                         71
...                                        ...
US     chevrolet cavalier wagon             82
       chevrolet cavalier 2-door            82
       pontiac j2000 se hatchback           82
       dodge aries se                       82
       pontiac phoenix                      82
       ford fairmont futura                 82
       amc concord dl                       82
Europe volkswagen rabbit l                  82
Japan  mazda glc custom l                   82
       mazda glc custom                     82
US     plymouth horizon miser               82
       mercury lynx l                       82
Japan  nissan stanza xe                     82
       honda accord                         82
       toyota corolla                       82
       honda civic                          82
       honda civic (auto)                   82
       datsun 310 gx                        82
US     buick century limited                82
       oldsmobile cutlass ciera (diesel)    82
       chrysler lebaron medallion           82
       ford granada l                       82
Japan  toyota celica gt                     82
US     dodge charger 2.2                    82
       chevrolet camaro                     82
       ford mustang gl                      82
Europe vw pickup                            82
US     dodge rampage                        82
       ford ranger                          82
       chevy s-10                           82

[394 rows x 7 columns]

In [17]:
table.index

MultiIndex(levels=[['Europe', 'Japan', 'US'], ['amc ambassador brougham', 'amc ambassador dpl', 'amc ambassador sst', 'amc concord', 'amc concord d/l', 'amc concord dl', 'amc concord dl 6', 'amc gremlin', 'amc hornet', 'amc hornet sportabout (sw)', 'amc matador', 'amc matador (sw)', 'amc pacer', 'amc pacer d/l', 'amc rebel sst', 'amc spirit dl', 'audi 100 ls', 'audi 100ls', 'audi 4000', 'audi 5000', 'audi 5000s (diesel)', 'audi fox', 'bmw 2002', 'bmw 320i', 'buick century', 'buick century 350', 'buick century limited', 'buick century luxus (sw)', 'buick century special', 'buick electra 225 custom', 'buick estate wagon (sw)', 'buick lesabre custom', 'buick opel isuzu deluxe', 'buick regal sport coupe (turbo)', 'buick skyhawk', 'buick skylark', 'buick skylark 320', 'buick skylark limited', 'cadillac eldorado', 'cadillac seville', 'capri ii', 'chevroelt chevelle malibu', 'chevrolet bel air', 'chevrolet camaro', 'chevrolet caprice classic', 'chevrolet cavalier', 'chevrolet cavalier 2-door', 'chevrolet cavalier wagon', 'chevrolet chevelle concours (sw)', 'chevrolet chevelle malibu', 'chevrolet chevelle malibu classic', 'chevrolet chevette', 'chevrolet citation', 'chevrolet concours', 'chevrolet impala', 'chevrolet malibu', 'chevrolet malibu classic (sw)', 'chevrolet monte carlo', 'chevrolet monte carlo landau', 'chevrolet monte carlo s', 'chevrolet monza 2+2', 'chevrolet nova', 'chevrolet nova custom', 'chevrolet vega', 'chevrolet vega (sw)', 'chevrolet vega 2300', 'chevrolet woody', 'chevy c10', 'chevy c20', 'chevy s-10', 'chrysler cordoba', 'chrysler lebaron medallion', 'chrysler lebaron salon', 'chrysler lebaron town @ country (sw)', 'chrysler new yorker brougham', 'chrysler newport royal', 'datsun 1200', 'datsun 200-sx', 'datsun 200sx', 'datsun 210', 'datsun 210 mpg', 'datsun 280-zx', 'datsun 310', 'datsun 310 gx', 'datsun 510', 'datsun 510 (sw)', 'datsun 510 hatchback', 'datsun 610', 'datsun 710', 'datsun 810', 'datsun 810 maxima', 'datsun b-210', 'datsun b210', 'datsun b210 gx', 'datsun f-10 hatchback', 'datsun pl510', 'dodge aries se', 'dodge aries wagon (sw)', 'dodge aspen', 'dodge aspen 6', 'dodge aspen se', 'dodge challenger se', 'dodge charger 2.2', 'dodge colt', 'dodge colt (sw)', 'dodge colt hardtop', 'dodge colt hatchback custom', 'dodge colt m/m', 'dodge coronet brougham', 'dodge coronet custom', 'dodge coronet custom (sw)', 'dodge d100', 'dodge d200', 'dodge dart custom', 'dodge diplomat', 'dodge magnum xe', 'dodge monaco (sw)', 'dodge monaco brougham', 'dodge omni', 'dodge rampage', 'dodge st. regis', 'fiat 124 sport coupe', 'fiat 124 tc', 'fiat 124b', 'fiat 128', 'fiat 131', 'fiat strada custom', 'fiat x1.9', 'ford country', 'ford country squire (sw)', 'ford escort 2h', 'ford escort 4w', 'ford f108', 'ford f250', 'ford fairmont', 'ford fairmont (auto)', 'ford fairmont (man)', 'ford fairmont 4', 'ford fairmont futura', 'ford fiesta', 'ford futura', 'ford galaxie 500', 'ford gran torino', 'ford gran torino (sw)', 'ford granada', 'ford granada ghia', 'ford granada gl', 'ford granada l', 'ford ltd', 'ford ltd landau', 'ford maverick', 'ford mustang', 'ford mustang gl', 'ford mustang ii', 'ford mustang ii 2+2', 'ford pinto', 'ford pinto (sw)', 'ford pinto runabout', 'ford ranger', 'ford thunderbird', 'ford torino', 'ford torino 500', 'hi 1200d', 'honda accord', 'honda accord cvcc', 'honda accord lx', 'honda civic', 'honda civic (auto)', 'honda civic 1300', 'honda civic 1500 gl', 'honda civic cvcc', 'honda prelude', 'maxda glc deluxe', 'maxda rx3', 'mazda 626', 'mazda glc', 'mazda glc 4', 'mazda glc custom', 'mazda glc custom l', 'mazda glc deluxe', 'mazda rx-4', 'mazda rx-7 gs', 'mazda rx2 coupe', 'mercedes benz 300d', 'mercedes-benz 240d', 'mercedes-benz 280s', 'mercury capri 2000', 'mercury capri v6', 'mercury cougar brougham', 'mercury grand marquis', 'mercury lynx l', 'mercury marquis', 'mercury marquis brougham', 'mercury monarch', 'mercury monarch ghia', 'mercury zephyr', 'mercury zephyr 6', 'nissan stanza xe', 'oldsmobile cutlass ciera (diesel)', 'oldsmobile cutlass ls', 'oldsmobile cutlass salon brougham', 'oldsmobile cutlass supreme', 'oldsmobile delta 88 royale', 'oldsmobile omega', 'oldsmobile omega brougham', 'oldsmobile starfire sx', 'oldsmobile vista cruiser', 'opel 1900', 'opel manta', 'peugeot 304', 'peugeot 504', 'peugeot 504 (sw)', 'peugeot 505s turbo diesel', 'peugeot 604sl', 'plymouth 'cuda 340', 'plymouth arrow gs', 'plymouth champ', 'plymouth cricket', 'plymouth custom suburb', 'plymouth duster', 'plymouth fury', 'plymouth fury gran sedan', 'plymouth fury iii', 'plymouth grand fury', 'plymouth horizon', 'plymouth horizon 4', 'plymouth horizon miser', 'plymouth horizon tc3', 'plymouth reliant', 'plymouth sapporo', 'plymouth satellite', 'plymouth satellite custom', 'plymouth satellite custom (sw)', 'plymouth satellite sebring', 'plymouth valiant', 'plymouth valiant custom', 'plymouth volare', 'plymouth volare custom', 'plymouth volare premier v8', 'pontiac astro', 'pontiac catalina', 'pontiac catalina brougham', 'pontiac firebird', 'pontiac grand prix', 'pontiac grand prix lj', 'pontiac j2000 se hatchback', 'pontiac lemans v6', 'pontiac phoenix', 'pontiac phoenix lj', 'pontiac safari (sw)', 'pontiac sunbird coupe', 'pontiac ventura sj', 'renault 12 (sw)', 'renault 12tl', 'renault 18i', 'renault 5 gtl', 'saab 99e', 'saab 99gle', 'saab 99le', 'subaru', 'subaru dl', 'toyota carina', 'toyota celica gt', 'toyota celica gt liftback', 'toyota corolla', 'toyota corolla 1200', 'toyota corolla 1600 (sw)', 'toyota corolla liftback', 'toyota corolla tercel', 'toyota corona', 'toyota corona hardtop', 'toyota corona liftback', 'toyota corona mark ii', 'toyota cressida', 'toyota mark ii', 'toyota starlet', 'toyota tercel', 'toyouta corona mark ii (sw)', 'triumph tr7 coupe', 'vokswagen rabbit', 'volkswagen 1131 deluxe sedan', 'volkswagen 411 (sw)', 'volkswagen dasher', 'volkswagen jetta', 'volkswagen model 111', 'volkswagen rabbit', 'volkswagen rabbit custom', 'volkswagen rabbit custom diesel', 'volkswagen rabbit l', 'volkswagen scirocco', 'volkswagen super beetle', 'volkswagen type 3', 'volvo 144ea', 'volvo 145e (sw)', 'volvo 244dl', 'volvo 245', 'volvo 264gl', 'volvo diesel', 'vw dasher (diesel)', 'vw pickup', 'vw rabbit', 'vw rabbit c (diesel)', 'vw rabbit custom']],
           labels=[[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 1, 0, 2, 1, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 0, 0, 0, 0, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 0, 2, 2, 0, 0, 0, 0, 2, 0, 1, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 2, 2, 0, 1, 1, 2, 0, 2, 0, 1, 0, 2, 2, 2, 2, 1, 2, 0, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 1, 2, 2, 2, 1, 0, 1, 0, 1, 0, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 0, 2, 0, 2, 2, 2, 1, 0, 2, 2, 2, 2, 0, 1, 2, 1, 2, 2, 2, 2, 0, 1, 1, 1, 1, 1, 2, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2], [49, 36, 230, 14, 160, 141, 54, 222, 240, 1, 101, 214, 57, 30, 272, 219, 8, 150, 95, 280, 210, 16, 256, 22, 7, 133, 68, 112, 162, 95, 65, 269, 7, 231, 49, 161, 10, 54, 241, 141, 222, 116, 129, 249, 9, 64, 242, 151, 186, 207, 209, 123, 265, 76, 284, 217, 270, 105, 291, 63, 157, 54, 240, 222, 141, 2, 191, 31, 202, 75, 182, 11, 48, 143, 232, 293, 281, 211, 252, 156, 85, 277, 104, 266, 25, 10, 55, 142, 109, 192, 44, 148, 221, 74, 29, 0, 234, 62, 8, 150, 219, 290, 54, 128, 218, 206, 7, 261, 63, 87, 173, 155, 187, 121, 59, 243, 124, 208, 17, 292, 113, 258, 274, 203, 219, 8, 61, 92, 155, 265, 63, 50, 10, 233, 142, 27, 110, 143, 11, 21, 282, 208, 269, 88, 103, 124, 122, 166, 259, 127, 235, 61, 193, 150, 240, 42, 223, 148, 24, 41, 10, 220, 34, 60, 153, 264, 155, 7, 239, 269, 282, 88, 155, 285, 12, 17, 210, 294, 258, 170, 125, 207, 40, 103, 253, 50, 108, 10, 142, 234, 61, 150, 8, 51, 66, 300, 166, 100, 145, 251, 13, 285, 91, 264, 155, 295, 238, 210, 274, 185, 39, 67, 132, 111, 164, 32, 255, 215, 94, 44, 201, 117, 188, 53, 35, 237, 144, 244, 58, 70, 159, 286, 250, 267, 154, 51, 107, 260, 282, 89, 23, 180, 287, 139, 179, 93, 170, 200, 114, 194, 248, 55, 135, 136, 236, 3, 28, 195, 98, 4, 58, 33, 140, 115, 51, 269, 84, 118, 263, 229, 205, 77, 19, 296, 257, 213, 289, 165, 246, 196, 137, 6, 99, 44, 149, 189, 120, 30, 129, 56, 73, 302, 172, 106, 15, 183, 38, 210, 200, 224, 227, 79, 126, 37, 52, 204, 247, 300, 268, 51, 82, 52, 134, 3, 98, 18, 271, 174, 86, 264, 175, 103, 79, 301, 298, 20, 184, 169, 260, 279, 81, 181, 278, 163, 228, 35, 97, 52, 228, 275, 216, 168, 259, 80, 276, 176, 225, 131, 130, 283, 254, 171, 264, 78, 174, 212, 297, 273, 90, 24, 199, 146, 72, 45, 47, 46, 245, 96, 247, 138, 5, 288, 178, 177, 226, 190, 197, 163, 264, 166, 167, 83, 26, 198, 71, 147, 262, 102, 43, 152, 299, 119, 158, 69]],
           names=['Origin', 'Model'])

In [20]:
# stacking displaying the data into column wise notation for each index. mostly useless
stacked_table=table.stack()
print(stacked_table)
unstacked_table=stacked_table.unstack()
unstacked_table #usually this does not work

Origin  Model
US      chevrolet chevelle malibu  MPG               18.0
                                   Cylinders          8.0
                                   Displacement     307.0
                                   Horsepower       130.0
                                   Weight          3504.0
                                   Acceleration      12.0
                                   Year              70.0
        buick skylark 320          MPG               15.0
                                   Cylinders          8.0
                                   Displacement     350.0
                                   Horsepower       165.0
                                   Weight          3693.0
                                   Acceleration      11.5
                                   Year              70.0
        plymouth satellite         MPG               18.0
                                   Cylinders          8.0
                                   Displacement     318.0
                                   Horsepower       150.0
                                   Weight          3436.0
                                   Acceleration      11.0
                                   Year              70.0
        amc rebel sst              MPG               16.0
                                   Cylinders          8.0
                                   Displacement     304.0
                                   Horsepower       150.0
                                   Weight          3433.0
                                   Acceleration      12.0
                                   Year              70.0
        ford torino                MPG               17.0
                                   Cylinders          8.0
                                                    ...
        ford mustang gl            Acceleration      15.6
                                   Year              82.0
Europe  vw pickup                  MPG               44.0
                                   Cylinders          4.0
                                   Displacement      97.0
                                   Horsepower        52.0
                                   Weight          2130.0
                                   Acceleration      24.6
                                   Year              82.0
US      dodge rampage              MPG               32.0
                                   Cylinders          4.0
                                   Displacement     135.0
                                   Horsepower        84.0
                                   Weight          2295.0
                                   Acceleration      11.6
                                   Year              82.0
        ford ranger                MPG               28.0
                                   Cylinders          4.0
                                   Displacement     120.0
                                   Horsepower        79.0
                                   Weight          2625.0
                                   Acceleration      18.6
                                   Year              82.0
        chevy s-10                 MPG               31.0
                                   Cylinders          4.0
                                   Displacement     119.0
                                   Horsepower        82.0
                                   Weight          2720.0
                                   Acceleration      19.4
                                   Year              82.0
Length: 2756, dtype: float64

ValueError: Index contains duplicate entries, cannot reshape

In [21]:
# this can also be used with already unstacked , i.e tabular (usual) data. 
#it will just unstack the indexes used in multi indexing
utable= table.unstack()
utable #again didn't worked

ValueError: Index contains duplicate entries, cannot reshape

In [22]:
filename = r'C:\Users\anshs\00ANSH_PYTHON\04-10-18 [1] NUMPY\PANDAS\cars.csv'
table = pd.read_csv(filename)
print(table)
table

                                 Model   MPG  Cylinders  Displacement  \
0            chevrolet chevelle malibu  18.0          8         307.0
1                    buick skylark 320  15.0          8         350.0
2                   plymouth satellite  18.0          8         318.0
3                        amc rebel sst  16.0          8         304.0
4                          ford torino  17.0          8         302.0
5                     ford galaxie 500  15.0          8         429.0
6                     chevrolet impala  14.0          8         454.0
7                    plymouth fury iii  14.0          8         440.0
8                     pontiac catalina  14.0          8         455.0
9                   amc ambassador dpl  15.0          8         390.0
10                 dodge challenger se  15.0          8         383.0
11                  plymouth 'cuda 340  14.0          8         340.0
12               chevrolet monte carlo  15.0          8         400.0
13             buick estate wagon (sw)  14.0          8         455.0
14               toyota corona mark ii  24.0          4         113.0
15                     plymouth duster  22.0          6         198.0
16                          amc hornet  18.0          6         199.0
17                       ford maverick  21.0          6         200.0
18                        datsun pl510  27.0          4          97.0
19        volkswagen 1131 deluxe sedan  26.0          4          97.0
20                         peugeot 504  25.0          4         110.0
21                         audi 100 ls  24.0          4         107.0
22                            saab 99e  25.0          4         104.0
23                            bmw 2002  26.0          4         121.0
24                         amc gremlin  21.0          6         199.0
25                           ford f250  10.0          8         360.0
26                           chevy c20  10.0          8         307.0
27                          dodge d200  11.0          8         318.0
28                            hi 1200d   9.0          8         304.0
29                        datsun pl510  27.0          4          97.0
..                                 ...   ...        ...           ...
364           chevrolet cavalier wagon  27.0          4         112.0
365          chevrolet cavalier 2-door  34.0          4         112.0
366         pontiac j2000 se hatchback  31.0          4         112.0
367                     dodge aries se  29.0          4         135.0
368                    pontiac phoenix  27.0          4         151.0
369               ford fairmont futura  24.0          4         140.0
370                     amc concord dl  23.0          4         151.0
371                volkswagen rabbit l  36.0          4         105.0
372                 mazda glc custom l  37.0          4          91.0
373                   mazda glc custom  31.0          4          91.0
374             plymouth horizon miser  38.0          4         105.0
375                     mercury lynx l  36.0          4          98.0
376                   nissan stanza xe  36.0          4         120.0
377                       honda accord  36.0          4         107.0
378                     toyota corolla  34.0          4         108.0
379                        honda civic  38.0          4          91.0
380                 honda civic (auto)  32.0          4          91.0
381                      datsun 310 gx  38.0          4          91.0
382              buick century limited  25.0          6         181.0
383  oldsmobile cutlass ciera (diesel)  38.0          6         262.0
384         chrysler lebaron medallion  26.0          4         156.0
385                     ford granada l  22.0          6         232.0
386                   toyota celica gt  32.0          4         144.0
387                  dodge charger 2.2  36.0          4         135.0
388                   chevrolet camaro  27.0          4         151.0
389                    ford mustang gl  27.0          4         140.0
390                          vw pickup  44.0          4          97.0
391                      dodge rampage  32.0          4         135.0
392                        ford ranger  28.0          4         120.0
393                         chevy s-10  31.0          4         119.0

     Horsepower  Weight  Acceleration  Year  Origin
0         130.0    3504          12.0    70      US
1         165.0    3693          11.5    70      US
2         150.0    3436          11.0    70      US
3         150.0    3433          12.0    70      US
4         140.0    3449          10.5    70      US
5         198.0    4341          10.0    70      US
6         220.0    4354           9.0    70      US
7         215.0    4312           8.5    70      US
8         225.0    4425          10.0    70      US
9         190.0    3850           8.5    70      US
10        170.0    3563          10.0    70      US
11        160.0    3609           8.0    70      US
12        150.0    3761           9.5    70      US
13        225.0    3086          10.0    70      US
14         95.0    2372          15.0    70   Japan
15         95.0    2833          15.5    70      US
16         97.0    2774          15.5    70      US
17         85.0    2587          16.0    70      US
18         88.0    2130          14.5    70   Japan
19         46.0    1835          20.5    70  Europe
20         87.0    2672          17.5    70  Europe
21         90.0    2430          14.5    70  Europe
22         95.0    2375          17.5    70  Europe
23        113.0    2234          12.5    70  Europe
24         90.0    2648          15.0    70      US
25        215.0    4615          14.0    70      US
26        200.0    4376          15.0    70      US
27        210.0    4382          13.5    70      US
28        193.0    4732          18.5    70      US
29         88.0    2130          14.5    71   Japan
..          ...     ...           ...   ...     ...
364        88.0    2640          18.6    82      US
365        88.0    2395          18.0    82      US
366        85.0    2575          16.2    82      US
367        84.0    2525          16.0    82      US
368        90.0    2735          18.0    82      US
369        92.0    2865          16.4    82      US
370         NaN    3035          20.5    82      US
371        74.0    1980          15.3    82  Europe
372        68.0    2025          18.2    82   Japan
373        68.0    1970          17.6    82   Japan
374        63.0    2125          14.7    82      US
375        70.0    2125          17.3    82      US
376        88.0    2160          14.5    82   Japan
377        75.0    2205          14.5    82   Japan
378        70.0    2245          16.9    82   Japan
379        67.0    1965          15.0    82   Japan
380        67.0    1965          15.7    82   Japan
381        67.0    1995          16.2    82   Japan
382       110.0    2945          16.4    82      US
383        85.0    3015          17.0    82      US
384        92.0    2585          14.5    82      US
385       112.0    2835          14.7    82      US
386        96.0    2665          13.9    82   Japan
387        84.0    2370          13.0    82      US
388        90.0    2950          17.3    82      US
389        86.0    2790          15.6    82      US
390        52.0    2130          24.6    82  Europe
391        84.0    2295          11.6    82      US
392        79.0    2625          18.6    82      US
393        82.0    2720          19.4    82      US

[394 rows x 9 columns]

,Model,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Year,Origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,US
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,US
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,70,US
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,70,US
4,ford torino,17.0,8,302.0,140.0,3449,10.5,70,US
5,ford galaxie 500,15.0,8,429.0,198.0,4341,10.0,70,US
6,chevrolet impala,14.0,8,454.0,220.0,4354,9.0,70,US
7,plymouth fury iii,14.0,8,440.0,215.0,4312,8.5,70,US
8,pontiac catalina,14.0,8,455.0,225.0,4425,10.0,70,US
9,amc ambassador dpl,15.0,8,390.0,190.0,3850,8.5,70,US
10,dodge challenger se,15.0,8,383.0,170.0,3563,10.0,70,US
11,plymouth 'cuda 340,14.0,8,340.0,160.0,3609,8.0,70,US
12,chevrolet monte carlo,15.0,8,400.0,150.0,3761,9.5,70,US
13,buick estate wagon (sw),14.0,8,455.0,225.0,3086,10.0,70,US
14,toyota corona mark ii,24.0,4,113.0,95.0,2372,15.0,70,Japan
15,plymouth duster,22.0,6,198.0,95.0,2833,15.5,70,US
16,amc hornet,18.0,6,199.0,97.0,2774,15.5,70,US
17,ford maverick,21.0,6,200.0,85.0,2587,16.0,70,US
18,datsun pl510,27.0,4,97.0,88.0,2130,14.5,70,Japan
19,volkswagen 1131 deluxe sedan,26.0,4,97.0,46.0,1835,20.5,70,Europe
20,peugeot 504,25.0,4,110.0,87.0,2672,17.5,70,Europe
21,audi 100 ls,24.0,4,107.0,90.0,2430,14.5,70,Europe
22,saab 99e,25.0,4,104.0,95.0,2375,17.5,70,Europe
23,bmw 2002,26.0,4,121.0,113.0,2234,12.5,70,Europe
24,amc gremlin,21.0,6,199.0,90.0,2648,15.0,70,US
25,ford f250,10.0,8,360.0,215.0,4615,14.0,70,US
26,chevy c20,10.0,8,307.0,200.0,4376,15.0,70,US
27,dodge d200,11.0,8,318.0,210.0,4382,13.5,70,US
28,hi 1200d,9.0,8,304.0,193.0,4732,18.5,70,US
29,datsun pl510,27.0,4,97.0,88.0,2130,14.5,71,Japan
...,...,...,...,...,...,...,...,...,...
364,chevrolet cavalier wagon,27.0,4,112.0,88.0,2640,18.6,82,US
365,chevrolet cavalier 2-door,34.0,4,112.0,88.0,2395,18.0,82,US
366,pontiac j2000 se hatchback,31.0,4,112.0,85.0,2575,16.2,82,US
367,dodge aries se,29.0,4,135.0,84.0,2525,16.0,82,US
368,pontiac phoenix,27.0,4,151.0,90.0,2735,18.0,82,US
369,ford fairmont futura,24.0,4,140.0,92.0,2865,16.4,82,US
370,amc concord dl,23.0,4,151.0,NaN,3035,20.5,82,US
371,volkswagen rabbit l,36.0,4,105.0,74.0,1980,15.3,82,Europe
372,mazda glc custom l,37.0,4,91.0,68.0,2025,18.2,82,Japan
373,mazda glc custom,31.0,4,91.0,68.0,1970,17.6,82,Japan
374,plymouth horizon miser,38.0,4,105.0,63.0,2125,14.7,82,US
375,mercury lynx l,36.0,4,98.0,70.0,2125,17.3,82,US
376,nissan stanza xe,36.0,4,120.0,88.0,2160,14.5,82,Japan
377,honda accord,36.0,4,107.0,75.0,2205,14.5,82,Japan
378,toyota corolla,34.0,4,108.0,70.0,2245,16.9,82,Japan
379,honda civic,38.0,4,91.0,67.0,1965,15.0,82,Japan
380,honda civic (auto),32.0,4,91.0,67.0,1965,15.7,82,Japan
381,datsun 310 gx,38.0,4,91.0,67.0,1995,16.2,82,Japan
382,buick century limited,25.0,6,181.0,110.0,2945,16.4,82,US
383,oldsmobile cutlass ciera (diesel),38.0,6,262.0,85.0,3015,17.0,82,US
384,chrysler lebaron medallion,26.0,4,156.0,92.0,2585,14.5,82,US
385,ford granada l,22.0,6,232.0,112.0,2835,14.7,82,US
386,toyota celica gt,32.0,4,144.0,96.0,2665,13.9,82,Japan
387,dodge charger 2.2,36.0,4,135.0,84.0,2370,13.0,82,US
388,chevrolet camaro,27.0,4,151.0,90.0,2950,17.3,82,US
389,ford mustang gl,27.0,4,140.0,86.0,2790,15.6,82,US
390,vw pickup,44.0,4,97.0,52.0,2130,24.6,82,Europe
391,dodge rampage,32.0,4,135.0,84.0,2295,11.6,82,US
392,ford ranger,28.0,4,120.0,79.0,2625,18.6,82,US
393,chevy s-10,31.0,4,119.0,82.0,2720,19.4,82,US

In [24]:
# unpivoting/melting
"""
i think the nomenclature is wrong , because
1) it has no relation with pivoting whatsoever
2) it has no relation with multi indexing or converting multindex to singleindex ore something
3) it looks like an ugly stack, in stack we had 

    US  chevrolet chevelle malibu MPG       18
                                  year    2001
                                  xyz       v1
                                 xyz2       v2
                                 xyz3       v3
                                 ...
                                  
    US  ford torino               MPG       17
                                  year    1999
                                  xyz      v1b
                                 xyz2      v2b
                                 xyz3      v3b
                                 ..
   But here we got :
   US     ford_ranger           MPG      18.0
   US     chevy s-12            MPG      12.0
   ...
   US     ford_ranger           Year      82.0
   US     chevy s-12            Year      89.0
   
    

"""
print(table.melt(id_vars=['Origin','Model']))
table.melt(id_vars=['Origin','Model'])

      Origin                              Model variable  value
0         US          chevrolet chevelle malibu      MPG   18.0
1         US                  buick skylark 320      MPG   15.0
2         US                 plymouth satellite      MPG   18.0
3         US                      amc rebel sst      MPG   16.0
4         US                        ford torino      MPG   17.0
5         US                   ford galaxie 500      MPG   15.0
6         US                   chevrolet impala      MPG   14.0
7         US                  plymouth fury iii      MPG   14.0
8         US                   pontiac catalina      MPG   14.0
9         US                 amc ambassador dpl      MPG   15.0
10        US                dodge challenger se      MPG   15.0
11        US                 plymouth 'cuda 340      MPG   14.0
12        US              chevrolet monte carlo      MPG   15.0
13        US            buick estate wagon (sw)      MPG   14.0
14     Japan              toyota corona mark ii      MPG   24.0
15        US                    plymouth duster      MPG   22.0
16        US                         amc hornet      MPG   18.0
17        US                      ford maverick      MPG   21.0
18     Japan                       datsun pl510      MPG   27.0
19    Europe       volkswagen 1131 deluxe sedan      MPG   26.0
20    Europe                        peugeot 504      MPG   25.0
21    Europe                        audi 100 ls      MPG   24.0
22    Europe                           saab 99e      MPG   25.0
23    Europe                           bmw 2002      MPG   26.0
24        US                        amc gremlin      MPG   21.0
25        US                          ford f250      MPG   10.0
26        US                          chevy c20      MPG   10.0
27        US                         dodge d200      MPG   11.0
28        US                           hi 1200d      MPG    9.0
29     Japan                       datsun pl510      MPG   27.0
...      ...                                ...      ...    ...
2728      US           chevrolet cavalier wagon     Year   82.0
2729      US          chevrolet cavalier 2-door     Year   82.0
2730      US         pontiac j2000 se hatchback     Year   82.0
2731      US                     dodge aries se     Year   82.0
2732      US                    pontiac phoenix     Year   82.0
2733      US               ford fairmont futura     Year   82.0
2734      US                     amc concord dl     Year   82.0
2735  Europe                volkswagen rabbit l     Year   82.0
2736   Japan                 mazda glc custom l     Year   82.0
2737   Japan                   mazda glc custom     Year   82.0
2738      US             plymouth horizon miser     Year   82.0
2739      US                     mercury lynx l     Year   82.0
2740   Japan                   nissan stanza xe     Year   82.0
2741   Japan                       honda accord     Year   82.0
2742   Japan                     toyota corolla     Year   82.0
2743   Japan                        honda civic     Year   82.0
2744   Japan                 honda civic (auto)     Year   82.0
2745   Japan                      datsun 310 gx     Year   82.0
2746      US              buick century limited     Year   82.0
2747      US  oldsmobile cutlass ciera (diesel)     Year   82.0
2748      US         chrysler lebaron medallion     Year   82.0
2749      US                     ford granada l     Year   82.0
2750   Japan                   toyota celica gt     Year   82.0
2751      US                  dodge charger 2.2     Year   82.0
2752      US                   chevrolet camaro     Year   82.0
2753      US                    ford mustang gl     Year   82.0
2754  Europe                          vw pickup     Year   82.0
2755      US                      dodge rampage     Year   82.0
2756      US                        ford ranger     Year   82.0
2757      US                         chevy s-10     Year   82.0

[2758 rows x 4 columns]

      Origin                              Model variable  value
0         US          chevrolet chevelle malibu      MPG   18.0
1         US                  buick skylark 320      MPG   15.0
2         US                 plymouth satellite      MPG   18.0
3         US                      amc rebel sst      MPG   16.0
4         US                        ford torino      MPG   17.0
5         US                   ford galaxie 500      MPG   15.0
6         US                   chevrolet impala      MPG   14.0
7         US                  plymouth fury iii      MPG   14.0
8         US                   pontiac catalina      MPG   14.0
9         US                 amc ambassador dpl      MPG   15.0
10        US                dodge challenger se      MPG   15.0
11        US                 plymouth 'cuda 340      MPG   14.0
12        US              chevrolet monte carlo      MPG   15.0
13        US            buick estate wagon (sw)      MPG   14.0
14     Japan              toyota corona mark ii      MPG   24.0
15        US                    plymouth duster      MPG   22.0
16        US                         amc hornet      MPG   18.0
17        US                      ford maverick      MPG   21.0
18     Japan                       datsun pl510      MPG   27.0
19    Europe       volkswagen 1131 deluxe sedan      MPG   26.0
20    Europe                        peugeot 504      MPG   25.0
21    Europe                        audi 100 ls      MPG   24.0
22    Europe                           saab 99e      MPG   25.0
23    Europe                           bmw 2002      MPG   26.0
24        US                        amc gremlin      MPG   21.0
25        US                          ford f250      MPG   10.0
26        US                          chevy c20      MPG   10.0
27        US                         dodge d200      MPG   11.0
28        US                           hi 1200d      MPG    9.0
29     Japan                       datsun pl510      MPG   27.0
...      ...                                ...      ...    ...
2728      US           chevrolet cavalier wagon     Year   82.0
2729      US          chevrolet cavalier 2-door     Year   82.0
2730      US         pontiac j2000 se hatchback     Year   82.0
2731      US                     dodge aries se     Year   82.0
2732      US                    pontiac phoenix     Year   82.0
2733      US               ford fairmont futura     Year   82.0
2734      US                     amc concord dl     Year   82.0
2735  Europe                volkswagen rabbit l     Year   82.0
2736   Japan                 mazda glc custom l     Year   82.0
2737   Japan                   mazda glc custom     Year   82.0
2738      US             plymouth horizon miser     Year   82.0
2739      US                     mercury lynx l     Year   82.0
2740   Japan                   nissan stanza xe     Year   82.0
2741   Japan                       honda accord     Year   82.0
2742   Japan                     toyota corolla     Year   82.0
2743   Japan                        honda civic     Year   82.0
2744   Japan                 honda civic (auto)     Year   82.0
2745   Japan                      datsun 310 gx     Year   82.0
2746      US              buick century limited     Year   82.0
2747      US  oldsmobile cutlass ciera (diesel)     Year   82.0
2748      US         chrysler lebaron medallion     Year   82.0
2749      US                     ford granada l     Year   82.0
2750   Japan                   toyota celica gt     Year   82.0
2751      US                  dodge charger 2.2     Year   82.0
2752      US                   chevrolet camaro     Year   82.0
2753      US                    ford mustang gl     Year   82.0
2754  Europe                          vw pickup     Year   82.0
2755      US                      dodge rampage     Year   82.0
2756      US                        ford ranger     Year   82.0
2757      US                         chevy s-10     Year   82.0

[2758 rows x 4 columns]

In [25]:
print(table.melt(id_vars=['Origin','Model'],value_vars=['Year','Acceleration']))# limits the value variable to only 2
table.melt(id_vars=['Origin','Model'],value_vars=['Year','Acceleration'])

     Origin                              Model      variable  value
0        US          chevrolet chevelle malibu          Year   70.0
1        US                  buick skylark 320          Year   70.0
2        US                 plymouth satellite          Year   70.0
3        US                      amc rebel sst          Year   70.0
4        US                        ford torino          Year   70.0
5        US                   ford galaxie 500          Year   70.0
6        US                   chevrolet impala          Year   70.0
7        US                  plymouth fury iii          Year   70.0
8        US                   pontiac catalina          Year   70.0
9        US                 amc ambassador dpl          Year   70.0
10       US                dodge challenger se          Year   70.0
11       US                 plymouth 'cuda 340          Year   70.0
12       US              chevrolet monte carlo          Year   70.0
13       US            buick estate wagon (sw)          Year   70.0
14    Japan              toyota corona mark ii          Year   70.0
15       US                    plymouth duster          Year   70.0
16       US                         amc hornet          Year   70.0
17       US                      ford maverick          Year   70.0
18    Japan                       datsun pl510          Year   70.0
19   Europe       volkswagen 1131 deluxe sedan          Year   70.0
20   Europe                        peugeot 504          Year   70.0
21   Europe                        audi 100 ls          Year   70.0
22   Europe                           saab 99e          Year   70.0
23   Europe                           bmw 2002          Year   70.0
24       US                        amc gremlin          Year   70.0
25       US                          ford f250          Year   70.0
26       US                          chevy c20          Year   70.0
27       US                         dodge d200          Year   70.0
28       US                           hi 1200d          Year   70.0
29    Japan                       datsun pl510          Year   71.0
..      ...                                ...           ...    ...
758      US           chevrolet cavalier wagon  Acceleration   18.6
759      US          chevrolet cavalier 2-door  Acceleration   18.0
760      US         pontiac j2000 se hatchback  Acceleration   16.2
761      US                     dodge aries se  Acceleration   16.0
762      US                    pontiac phoenix  Acceleration   18.0
763      US               ford fairmont futura  Acceleration   16.4
764      US                     amc concord dl  Acceleration   20.5
765  Europe                volkswagen rabbit l  Acceleration   15.3
766   Japan                 mazda glc custom l  Acceleration   18.2
767   Japan                   mazda glc custom  Acceleration   17.6
768      US             plymouth horizon miser  Acceleration   14.7
769      US                     mercury lynx l  Acceleration   17.3
770   Japan                   nissan stanza xe  Acceleration   14.5
771   Japan                       honda accord  Acceleration   14.5
772   Japan                     toyota corolla  Acceleration   16.9
773   Japan                        honda civic  Acceleration   15.0
774   Japan                 honda civic (auto)  Acceleration   15.7
775   Japan                      datsun 310 gx  Acceleration   16.2
776      US              buick century limited  Acceleration   16.4
777      US  oldsmobile cutlass ciera (diesel)  Acceleration   17.0
778      US         chrysler lebaron medallion  Acceleration   14.5
779      US                     ford granada l  Acceleration   14.7
780   Japan                   toyota celica gt  Acceleration   13.9
781      US                  dodge charger 2.2  Acceleration   13.0
782      US                   chevrolet camaro  Acceleration   17.3
783      US                    ford mustang gl  Acceleration   15.6
784  Europe                          vw pickup  Acceleration   24.6
785      US                      dodge rampage  Acceleration   11.6
786      US                        ford ranger  Acceleration   18.6
787      US                         chevy s-10  Acceleration   19.4

[788 rows x 4 columns]

     Origin                              Model      variable  value
0        US          chevrolet chevelle malibu          Year   70.0
1        US                  buick skylark 320          Year   70.0
2        US                 plymouth satellite          Year   70.0
3        US                      amc rebel sst          Year   70.0
4        US                        ford torino          Year   70.0
5        US                   ford galaxie 500          Year   70.0
6        US                   chevrolet impala          Year   70.0
7        US                  plymouth fury iii          Year   70.0
8        US                   pontiac catalina          Year   70.0
9        US                 amc ambassador dpl          Year   70.0
10       US                dodge challenger se          Year   70.0
11       US                 plymouth 'cuda 340          Year   70.0
12       US              chevrolet monte carlo          Year   70.0
13       US            buick estate wagon (sw)          Year   70.0
14    Japan              toyota corona mark ii          Year   70.0
15       US                    plymouth duster          Year   70.0
16       US                         amc hornet          Year   70.0
17       US                      ford maverick          Year   70.0
18    Japan                       datsun pl510          Year   70.0
19   Europe       volkswagen 1131 deluxe sedan          Year   70.0
20   Europe                        peugeot 504          Year   70.0
21   Europe                        audi 100 ls          Year   70.0
22   Europe                           saab 99e          Year   70.0
23   Europe                           bmw 2002          Year   70.0
24       US                        amc gremlin          Year   70.0
25       US                          ford f250          Year   70.0
26       US                          chevy c20          Year   70.0
27       US                         dodge d200          Year   70.0
28       US                           hi 1200d          Year   70.0
29    Japan                       datsun pl510          Year   71.0
..      ...                                ...           ...    ...
758      US           chevrolet cavalier wagon  Acceleration   18.6
759      US          chevrolet cavalier 2-door  Acceleration   18.0
760      US         pontiac j2000 se hatchback  Acceleration   16.2
761      US                     dodge aries se  Acceleration   16.0
762      US                    pontiac phoenix  Acceleration   18.0
763      US               ford fairmont futura  Acceleration   16.4
764      US                     amc concord dl  Acceleration   20.5
765  Europe                volkswagen rabbit l  Acceleration   15.3
766   Japan                 mazda glc custom l  Acceleration   18.2
767   Japan                   mazda glc custom  Acceleration   17.6
768      US             plymouth horizon miser  Acceleration   14.7
769      US                     mercury lynx l  Acceleration   17.3
770   Japan                   nissan stanza xe  Acceleration   14.5
771   Japan                       honda accord  Acceleration   14.5
772   Japan                     toyota corolla  Acceleration   16.9
773   Japan                        honda civic  Acceleration   15.0
774   Japan                 honda civic (auto)  Acceleration   15.7
775   Japan                      datsun 310 gx  Acceleration   16.2
776      US              buick century limited  Acceleration   16.4
777      US  oldsmobile cutlass ciera (diesel)  Acceleration   17.0
778      US         chrysler lebaron medallion  Acceleration   14.5
779      US                     ford granada l  Acceleration   14.7
780   Japan                   toyota celica gt  Acceleration   13.9
781      US                  dodge charger 2.2  Acceleration   13.0
782      US                   chevrolet camaro  Acceleration   17.3
783      US                    ford mustang gl  Acceleration   15.6
784  Europe                          vw pickup  Acceleration   24.6
785      US                      dodge rampage  Acceleration   11.6
786      US                        ford ranger  Acceleration   18.6
787      US                         chevy s-10  Acceleration   19.4

[788 rows x 4 columns]